apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-vivek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-vivek
  template:
    metadata:
      labels:
        app: healthcare-vivek
    spec:
      containers:
      - name: healthcare-vivek
        image: vivekkamurthy/healthcare-vivek:1
        ports:
        - containerPort: 8082
        
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-vivek
spec:
  selector:
    app: healthcare-vivek  
  type: NodePort
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 30007
